# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Daniel Fuentes
email: imdanfuentes@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Front-end web developer that likes to make cool websites and apps in Harrisburg, Pa.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://imdanielfuentes.com/" # the base hostname & protocol for your site
twitter_username: FuentesDPro
github_username:  dfuentes22
permalink: /:title

# Build settings
markdown: kramdown

#scripts
google_analytics: "UA-72527601-1"
